# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # RDS

  Creates an RDS database along with all required resources such as a parameter group, subnet group, security group, etc...

  The intended purpose is to be a 100% solution to 95% of the use cases

  Things to note:

  - Adds an alarm for 75% usage
  - Creates a randomized id for the final snapshop to support multiple database replacements
  - The Parameter groups can be namespaced to support major version upgrades

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  