# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # Security Group

  Thin wrapper around a security group to allow inline specification of ingress/egree rules without causing the normal issues

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  