# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # SQS

  Creates an SQS Queue with an optional KMS key configuration and policy configuration

  ## Creating a queue with the AWS provided KMS Key

  ```hcl
  module "example_queue" {
    source = "github.com/myoolala/terraform-aws/modules//sqs"

    name         = "test-integration-queue"
    kms = {
      key = "alias/aws/sqs"
    }
  }
  ```

  [More examples can be found here](../../tests/sqs/)

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  