# .terraform-docs.yml

header-from: main.tf

settings:
 type: false

sort:
  enabled: true
  by: required

content: |-
  {{ .Header }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  