# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # Load Balancer

  Still WIP, creates an AWS PowerTools layer to be used with Python based lambda functions

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  