# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # Lambda S3 UI

  Creates a Lambda based S3 proxy sitting behind an ALB to handle UI requests. The main intention is to add logic for SPA apps where a 404 isn't necessarily a 404

  This is intended for small or burst scale where a fargate service cannot compete in price

  ## Key notes:

  - If your system is 100% internal, you will need a VPC endpoint such that the target group can reach the Lambda service. 
  - In addition, the lambda itself will need a VPC endpoint if it lives inside a private only network to reach s3
  - Otherwise, hosting this in a VPC is not required
  - All responses are cache via a configuration
  - Cache busting headers will bust the in memory RunTime cache
  - If you are using multiple hosts on the load balancer, you can enable embedded metrics per host to see the count per site

  ## Examples:

  ```hcl
    resource "aws_lb_target_group" "forwarder" {
      name        = "tg_name"
      protocol    = "HTTPS"
      vpc_id      = null
      target_type = "lambda"
    }

    module "lambda-ui" {
      source = "github.com/myoolala/terraform-aws/modules/lambda-s3-ui"

      lambda_name = "ui-lambda"
      alb_tg_arn  = aws_lb_target_group.forwarder.arn
      config = {
        bucket = "fu"
        prefix = "bar"
      }
      vpc_config = null
    }
  ```

  [More examples can be found here](../../tests/ui-lambda)

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  