# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # SNS

  Creates an SNS topic with an optional KMS key configuration and policy configuration

  [Examples can be found here](../../tests/sns/)

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  