# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # SecretsManager

  Creates a set of secrets in SecretsManager using a single KMS key. Then returns a variety of lists meant for simple integration with other services

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  