# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # KMS Key

  Automates creating a KMS key. The man purpose of this module is to reduce the policy work to open the key to the account and couple an Alias to it

  This does support overriding the default policy. [Follow the examples to learn more](../../tests/kms/)

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  