# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # Task Definition

  Creates a Task Definition for an ECS service/task. Automates the IAM provisioning and creating the Task Definition itself

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  