# .terraform-docs.yml

settings:
  type: true

sort:
  enabled: true
  by: required

content: |-
  # S3 Bucket

  Creates an S3 bucket with some automated behavior like setting encryption and policies

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}  